name: Trigger image build

on: 
 push:
   tags:
     - '*'
 workflow_dispatch:
   inputs:
     tag:
       description: The tag for which to create the image
       
jobs:
  trigger_main_build:
    runs-on: ubuntu-latest
    steps:
      - name: Get build tag
        id: get_tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "::set-output name=tag::${{ github.ref }}"
          else
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          fi
      - name: Echo tag
        run: |
          echo "${{ steps.get_tag.outputs.tag }}"
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build TinyTicker RPi image
          repo: loiccoyle/private.actionsrunner
          token: ${{ secrets.ACCESS_TOKEN }}
          inputs: '{ "repo_ref": "${{ steps.get_tag.outputs.tag }}" }'
          ref: refs/heads/main # https://github.com/benc-uk/workflow-dispatch/issues/11
